num = int(input()) count = int(input())
print(count % num == 0, end = " ") count = int(input())
print(count % num == 0, end = " ") count = int(input())
print(count % num == 0, end = " ") count = int(input())
print(count % num == 0, end = " ")
